import type { Metadata } from "next";
import { Geist,Anek_Telugu,Geist_Mono} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geitMono = Geist_Mono({
  variable:'---font-geist-mono',
  subsets:['latin']
})
const AnekTelugu = Anek_Telugu({
  variable: "--font-caption",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Yvan FOTSO . Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(geistSans.variable,
          geitMono.variable,AnekTelugu.variable,'font-sans h-full')}
      >
        {children}
      </body>
    </html>
  );
}
